name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier:check

      - name: Lint
        run: npm run eslint

      - name: Unit test
        run: npm run test
